<?php
$emoticon = array(
     "=))" => "<img class='emoticon' src='assets/emoji/rolling.gif'>",
     ":))" => "<img class='emoticon' src='assets/emoji/hehe.gif'>",
     ":)" => "<img class='emoticon' src='assets/emoji/smug.gif'>",
	 ";)" => "<img class='emoticon' src='assets/emoji/nhaymat.gif'>",
     ":d" => "<img class='emoticon' src='assets/emoji/laughing.gif'>",
	 ":D" => "<img class='emoticon' src='assets/emoji/laughing.gif'>",
     ":p" => "<img class='emoticon' src='assets/emoji/phbbt.gif'>",
	 ":P" => "<img class='emoticon' src='assets/emoji/phbbt.gif'>",
     ":*" => "<img class='emoticon' src='assets/emoji/love.gif'>",
     "@@" => "<img class='emoticon' src='assets/emoji/dancing.gif'>",
     ">_<" => "<img class='emoticon' src='assets/emoji/notworthy.gif'>",
     ":o" => "<img class='emoticon' src='assets/emoji/ngacnhien.gif'>",
	 ":O" => "<img class='emoticon' src='assets/emoji/ngacnhien.gif'>",
	 "o.O" => "<img class='emoticon' src='assets/emoji/oo.png'>",
	 "O.o" => "<img class='emoticon' src='assets/emoji/oo.png'>",
	 "O.O" => "<img class='emoticon' src='assets/emoji/oo.png'>",
     ":3" => "<img class='emoticon' src='assets/emoji/ohgoon.gif'>",
     "(y)" => "<img class='emoticon' src='assets/emoji/like.png'>",
     ":(" => "<img class='emoticon' src='assets/emoji/buon.gif'>",
     ":((" => "<img class='emoticon' src='assets/emoji/khoc.gif'>",
     ":v" => "<img class='emoticon' src='assets/emoji/whistling.gif'>",
     "._." => "<img class='emoticon' src='assets/emoji/skull.gif'>",
     ":$" => "<img class='emoticon' src='assets/emoji/money.gif'>",
     "-_-" => "<img class='emoticon' src='assets/emoji/straight.gif'>",
     ":/" => "<img class='emoticon' src='assets/emoji/thinking.gif'>",
	 "<3" => "<img class='emoticon' src='assets/emoji/tim.png'>",
	 ":poop:" => "<img class='emoticon' src='assets/emoji/shit.png'>",
	 "like" => "<img class='emoticon' src='assets/emoji/ungho.gif'>",
);
?>